abstract: PSON(PerlScript Object Notation) Module
author: Tomohiro Teranishi <tomohiro.teranishi@gmail.com>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Acme-PSON
no_index: 
  directory: 
    - inc
    - t
requires: 
  Readonly: 0
  Test::More: 0
version: 0.02
